<?php 
$click = 0;
$classephrase = "";
if($click == 0){
    $classephrase = "Phrases";
}
else{
    $classephrase = "PhrasesLu";
}
$sentence1 = "Je m'apelle Jambon";
$sentence2 = "Le jambon c'est bon";
$sentence3 = "hjkhfjkehf";
$sentence4 = "jgldgdmg";
$sentence5 = "ksngklsgseg";
$sentence6 = "jhfjshfe";
$sentence7 = "lksglkn";
$sentence8 = "ksefkgsg";
$sentence9 = "kjzeklfzef";
$sentence10 = "kjdkfjlskf";
?>

<h2 class="Titre text-center" > Mes connaissances</h2>

graphe...

