<h1>Utilisateur</h1>
<h2>Connaissances</h2>
<div class="panel panel-default">
  <div class="panel-body">
    <span class="label label-default">Mot</span>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Graphe de connaissance</h3>
  </div>
  <div class="panel-body">
  </div>
</div>
<h2>Derni&egrave;res recherches</h2>
<span class="label label-default">Mot</span>