<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Knowledge\Module'                        => __DIR__ . '/Module.php',
    'Knowledge\Controller\KnowledgeController' => __DIR__ . '/src/Knowledge/Controller/KnowledgeController.php',
    'KnowledgeTest\Framework\TestCase'        => __DIR__ . '/tests/Knowledge/Framework/TestCase.php',
    'KnowledgeTest\SampleTest'                => __DIR__ . '/tests/Knowledge/SampleTest.php',
);
