<section class="jumbotron">
    <div class="container">
        <h1>Bienvenue sur Lingueetech</h1>
        <p>Apprenez l'anglais &agrave; votre rythme avec Lingueetech. Recherchez des expressions, ajoutez du vocabulaire &agrave; vos connaissances puis laissez Lingueetech vous guider. Commencez d&egrave;s maintenant l'experience !</p>
        <p><a class="btn btn-primary btn-lg" role="button">Commencer &raquo;</a></p>
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2 class="text-center">Avancez &agrave; votre rythme</h2>
                <p>Choisissez ce que vous souhaitez apprendre, &agrave; votre rythme, en utilisant la fonction de recherche ou en laissant Lingueetech &eacute;ttofer vos connaissances.</p>
            </div>
            <div class="col-md-4">
                <h2 class="text-center">Des milliers de phrases</h2>
                <p>Bas&eacute; sur le projet Tatoba et sa base de donn&eacute; foisonnante, Lingueetech met &agrave; votre disposition plusieurs centaines de milliers de phrase, en anglais et en fran&ccedil;ais.</p>
            </div>
            <div class="col-md-4">
                <h2 class="text-center">Un projet &eacute;tudiant</h2>
                <p>Lingueetech est un projet &eacute;tudiant r&eacute;alis&eacute; dans le cadre de l'option d'extraction textuelle de quatri&egrave;me ann&eacute;e.</p>
            </div>
        </div>
    </div>
</section>