<?php echo $this->doctype(); ?>

<html lang="en">

<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('LingueeTech')->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
								
								echo $this->headMeta ()->appendName ( 'viewport', 'width=device-width, initial-scale=1.0' )->appendHttpEquiv ( 'X-UA-Compatible', 'IE=edge' )?>

        <!-- Le styles -->
        <?php
								
								echo $this->headLink ( array (
										'rel' => 'shortcut icon',
										'type' => 'image/vnd.microsoft.icon',
										'href' => $this->basePath () . '/img/logo_polytech.ico' 
								) )->prependStylesheet ( $this->basePath () . '/css/style.css' )->prependStylesheet ( $this->basePath () . '/css/bootstrap-theme.min.css' )->prependStylesheet ( $this->basePath () . '/css/bootstrap.min.css' )?>

        <!-- Scripts -->
        <?php
								
								echo $this->headScript ()->prependFile ( $this->basePath () . '/js/bootstrap.min.js' )->prependFile ( $this->basePath () . '/js/jquery.min.js' )->prependFile ( $this->basePath () . '/js/respond.min.js', 'text/javascript', array (
										'conditional' => 'lt IE 9' 
								) )->prependFile ( $this->basePath () . '/js/html5shiv.js', 'text/javascript', array (
										'conditional' => 'lt IE 9' 
								) );
								?>

    </head>
<body>
	<header id="header" role=banner>
		<nav class="navbar navbar-pills navbar-static-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse"
						data-target=".navbar-collapse">
						<span class="icon-bar"></span> <span class="icon-bar"></span> <span
							class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img
						src="<?php echo $this->basePath('img/logo_polytech.ico') ?>"
						alt="Zend Framework 2" />&nbsp;LingueeTech</a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li class="active"><a href="<?php echo $this->url('home') ?>">
								Rechercher</a></li>
						<li class="active"><a href="<?php echo $this->url('home') ?>">
								Guide-moi! </a></li>
						<li class="active"><a href="<?php echo $this->url('home') ?>"> Mes
								connaissances </a></li>
					</ul>
					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input type="text" class="form-control" placeholder="Recherche">
						</div>
						<button type="submit" class="btn btn-default">Rechercher</button>
					</form>
				</div>
				<!--/.nav-collapse -->
			</div>
		</nav>
	</header>
	<div class="container">
            <?php echo $this->content; ?>
        </div>
	<!-- /container -->


	<footer class="container bas">
	<hr>
		<ul class="nav nav-pills nav-justified">
			<li class="foot logoP"> <img src="<?php echo $this->basePath('img/polytech.png') ?>"
						alt="LogoP"></li>
			<li class="foot name"> Projet réalisé par : NOMS Prénom ... <br> Etudiants de Polytech Paris-Sud </li>
			<li class="foot"> <img id="univ" src="<?php echo $this->basePath('img/univ.png') ?>"
						alt="LogoU"></li> 
		</ul>
		</footer>
        <?php echo $this->inlineScript()?>
    </body>
</html>
