<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Sentence\Module'                        => __DIR__ . '/Module.php',
    'Sentence\Controller\SentenceController' => __DIR__ . '/src/Sentence/Controller/SentenceController.php',
    'SentenceTest\Framework\TestCase'        => __DIR__ . '/tests/Sentence/Framework/TestCase.php',
    'SentenceTest\SampleTest'                => __DIR__ . '/tests/Sentence/SampleTest.php',
);
