<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Follow\Module'                        => __DIR__ . '/Module.php',
    'Follow\Controller\FollowController' => __DIR__ . '/src/Follow/Controller/FollowController.php',
    'FollowTest\Framework\TestCase'        => __DIR__ . '/tests/Follow/Framework/TestCase.php',
    'FollowTest\SampleTest'                => __DIR__ . '/tests/Follow/SampleTest.php',
);
