<?php 
$click = 0;
$classephrase = "";
if($click == 0){
    $classephrase = "Phrases";
}
else{
    $classephrase = "PhrasesLu";
}
$motCherche = "Jambon"; // Mot chercher par l'utilisateur;
?>
<?php if($motCherche == ""):?>

<?php elseif ( $motCherche != "" ) :?>
<h2 class="Titre text-center" > Recherche : <?php echo $motCherche ?></h2>
<?php endif;?>
<script type="text/javascript">
 function enter(elem, id){
 
     elem.style.backgroundColor = '#CCFFCC';
    	    $(id).modal({
    	        'show' : true
    	    });
 }
</script>
<?php foreach ($sentences as $id => $sentence ):?>
<div class="PhraseEntiere" data-toggle="modal" data-target="#myModal">
    <div  class="Phrases" onclick="enter(this,'#m<?php echo $id ?>')">
        <span class="textPhrase"><?php echo $sentence  ?></span>
    </div>
</div>
<div class="modal fade" id="m<?php echo $id ?>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Regarde de plus près</h4>
      </div>
      <div class="modal-body">
        <p><?php echo $sentence?></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<?php endforeach;?> 
<button type="button" class=" bouton btn btn-info">Autres phrases</button>